project:
  type: website

execute:
  freeze: false

website:
  title: "Jury"
  search: false
  navbar:
    logo: "img/SwissEquestrian.png"
    background: "#00283c"
    left:
      - href: index.qmd
        text: Accueil

  sidebar:
    contents:
      - section: "Saison 2024"
        contents:
          - saisons/2024/Fenin_ACEF.qmd
          - saisons/2024/Crete.qmd
          - saisons/2024/Fenin.qmd

format:
  html:
    theme: [cosmo, "styles.scss"]
    toc: true
    execute:
      echo: false
      warning: false
  pdf:
    pdf-engine: xelatex
    papersize: a4
    mainfont: "FiraSans"
    mainfontoptions:
      - Ligatures=TeX
      - UprightFont = *-Light
      - ItalicFont = *-LightItalic
      - BoldFont = *-Regular
      - BoldItalicFont = *-Italic
    classoption: landscape
    colorlinks: false
    logo: img/SwissEquestrian.png
    geometry:
      - bindingoffset=0in
      - headheight=35pt
      - left=1.5cm
      - right=1.5cm
      - top=2.5cm
      - bottom=2cm
      - headsep=.5cm
      - footskip=1cm
    template-partials:
      - partials/title.tex
      - partials/pandoc.tex
      - partials/before-body.tex
    include-in-header:
      text: \usepackage{lastpage}
    execute:
      echo: false
      warning: false

editor: visual
