project:
  type: website

execute:
  freeze: false
  echo: false
  warning: false
  message: false

website:
  title: "Jury"
  search: false
  navbar:
    logo: "img/SwissEquestrian.png"
    background: "#00283c"
    left:
      - href: index.qmd
        text: Accueil

  sidebar:
    contents:
      - section: "Saison 2025"
        contents:
          - saisons/2025/Crete.qmd

format:
  html:
    theme: [cosmo, "styles.scss"]
    toc: true
    execute:
      echo: false
      warning: false
  se-doc-typst:
    flipped: true
