on:
  workflow_dispatch

name: Jury-Plan

jobs:
  jury-plan-ssh:
    name: Update fnchJury
    runs-on: ubuntu-latest
    steps:
    - name: Connect to Aeluin and update site
      uses: D3rHase/ssh-command-action@v0.2.1
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USER: ${{ secrets.SSH_USER }}
        PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        COMMAND: |
          cd /var/www/fsse-jury
          git pull
          quarto render
          rm -rf www
          cp -rf _site www
