on:
  workflow_dispatch

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

name: Jury-Plan

jobs:
  jury-plan-ssh:
    name: Update fnchJury
    runs-on: ubuntu-latest
    steps:
    - name: Connect to Aeluin and update site
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/fsse-jury
          quarto render
          cp -ru _site www
